api_endpoints:
  cpu: "https://api.example.com/cpu"
  gpu: "https://api.example.com/gpu"
  ssd: "https://api.example.com/ssd"
  ram: "https://api.example.com/ram"
current_system:
  cpu: "Intel Core i7-12700KF"
  gpu: "AMD RX 7900GRE"
  ssd: "Samsung 970 EVO 1TB"
  ram: "32GB DDR5"